name: CI

on:
  push:
    branches: [main, release, test, dev]
  pull_request:
    branches: [main, release, test, dev]

jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: action/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f    